<a href="https://colab.research.google.com/github/Abbos-Amirov/ai_foundation/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
pip install numpy

In [4]:
import numpy as np

arr = np.array ([1,2,3,4,5,])
print('array:',arr)

array: [1 2 3 4 5]



arr2 = np.array ([[1,2,3,4,5,], [1,3,4,5,6]])
print('array:',arr2)
arr2.shape

In [12]:
a = np.array([1, 2, 3])

b = a.astype(float)

print(b)

[1. 2. 3.]


In [13]:
z = np.zeros((2,3))

print(z)

[[0. 0. 0.]
 [0. 0. 0.]]


In [14]:
a = np.array([[1,2],[3,4]])

print(a.ndim)

2
